apiVersion: apps/v1
kind: Deployment
metadata:
  name: conway-deployment
spec:
  selector:
    matchLabels:
      app: conway-frontend-blue
  replicas: 2
  template:
    metadata:
      labels:
        app: conway-frontend-blue
    spec:
      containers:
        - name: conway-frontend-blue
          image: agmeteor/conway-game:stable
          ports:
            - containerPort: 80
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: frontend-workers