apiVersion: v1
kind: Service
metadata:
  name: conway-frontend-green-svc
spec:
  type: LoadBalancer
  selector:
    app: conway-frontend-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80